# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('UserId', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('UserKey', models.CharField(max_length=200)),
                ('GroupName', models.CharField(max_length=200)),
                ('Monedas', models.CharField(max_length=200)),
            ],
        ),
    ]
